const fs = require('fs');
let code = fs.readFileSync('src/ui.js', 'utf8');

// Wait, the logic is totally fine, maybe the problem in the test script is that the DOM elements inside index.html aren't accessible right away, or they are generated by something else?
