const moves = {
    "Tackle": {"power": 40, "type": "Normal", "category": "Physical"},
    "Vine Whip": {"power": 45, "type": "Grass", "category": "Physical"},
    "Razor Leaf": {"power": 55, "type": "Grass", "category": "Physical"},
    "Solar Beam": {"power": 120, "type": "Grass", "category": "Special"},
    "Scratch": {"power": 40, "type": "Normal", "category": "Physical"},
    "Ember": {"power": 40, "type": "Fire", "category": "Special"},
    "Slash": {"power": 70, "type": "Normal", "category": "Physical"},
    "Flamethrower": {"power": 90, "type": "Fire", "category": "Special"},
    "Fire Spin": {"power": 35, "type": "Fire", "category": "Special"},
    "Wing Attack": {"power": 60, "type": "Flying", "category": "Physical"},
    "Fire Blast": {"power": 110, "type": "Fire", "category": "Special"},
    "Water Gun": {"power": 40, "type": "Water", "category": "Special"},
    "Bite": {"power": 60, "type": "Dark", "category": "Physical"},
    "Bubble Beam": {"power": 65, "type": "Water", "category": "Special"},
    "Water Pulse": {"power": 60, "type": "Water", "category": "Special"},
    "Hydro Pump": {"power": 110, "type": "Water", "category": "Special"},
    "Skull Bash": {"power": 130, "type": "Normal", "category": "Physical"},
    "Flash Cannon": {"power": 80, "type": "Steel", "category": "Special"},
    "Blizzard": {"power": 110, "type": "Ice", "category": "Special"},
    "Bug Bite": {"power": 60, "type": "Bug", "category": "Physical"},
    "Confusion": {"power": 50, "type": "Psychic", "category": "Special"},
    "Gust": {"power": 40, "type": "Flying", "category": "Special"},
    "Psybeam": {"power": 65, "type": "Psychic", "category": "Special"},
    "Air Slash": {"power": 75, "type": "Flying", "category": "Special"},
    "Bug Buzz": {"power": 90, "type": "Bug", "category": "Special"},
    "Poison Sting": {"power": 15, "type": "Poison", "category": "Physical"},
    "Fury Attack": {"power": 15, "type": "Normal", "category": "Physical"},
    "Twineedle": {"power": 25, "type": "Bug", "category": "Physical"},
    "Pin Missile": {"power": 25, "type": "Bug", "category": "Physical"},
    "Poison Jab": {"power": 80, "type": "Poison", "category": "Physical"},
    "X-Scissor": {"power": 80, "type": "Bug", "category": "Physical"},
    "Quick Attack": {"power": 40, "type": "Normal", "category": "Physical"},
    "Hurricane": {"power": 110, "type": "Flying", "category": "Special"},
    "Hyper Fang": {"power": 80, "type": "Normal", "category": "Physical"},
    "Super Fang": {"power": 80, "type": "Normal", "category": "Physical"},
    "Crunch": {"power": 80, "type": "Dark", "category": "Physical"},
    "Double-Edge": {"power": 120, "type": "Normal", "category": "Physical"},
    "Peck": {"power": 35, "type": "Flying", "category": "Physical"},
    "Aerial Ace": {"power": 60, "type": "Flying", "category": "Physical"},
    "Drill Peck": {"power": 80, "type": "Flying", "category": "Physical"},
    "Drill Run": {"power": 80, "type": "Ground", "category": "Physical"},
    "Sky Attack": {"power": 140, "type": "Flying", "category": "Physical"},
    "Wrap": {"power": 15, "type": "Normal", "category": "Physical"},
    "Acid": {"power": 40, "type": "Poison", "category": "Special"},
    "Gunk Shot": {"power": 120, "type": "Poison", "category": "Physical"},
    "Earthquake": {"power": 100, "type": "Ground", "category": "Physical"},
    "Thundershock": {"power": 40, "type": "Electric", "category": "Special"},
    "Spark": {"power": 65, "type": "Electric", "category": "Physical"},
    "Slam": {"power": 80, "type": "Normal", "category": "Physical"},
    "Thunderbolt": {"power": 90, "type": "Electric", "category": "Special"},
    "Thunder": {"power": 110, "type": "Electric", "category": "Special"},
    "Volt Tackle": {"power": 120, "type": "Electric", "category": "Physical"},
    "Mud-Slap": {"power": 20, "type": "Ground", "category": "Special"},
    "Rollout": {"power": 30, "type": "Rock", "category": "Physical"},
    "Dig": {"power": 80, "type": "Ground", "category": "Physical"},
    "Poison Fang": {"power": 50, "type": "Poison", "category": "Physical"},
    "Body Slam": {"power": 85, "type": "Normal", "category": "Physical"},
    "Earth Power": {"power": 90, "type": "Ground", "category": "Special"},
    "Sludge Wave": {"power": 95, "type": "Poison", "category": "Special"},
    "Superpower": {"power": 120, "type": "Fighting", "category": "Physical"},
    "Horn Attack": {"power": 65, "type": "Normal", "category": "Physical"},
    "Megahorn": {"power": 120, "type": "Bug", "category": "Physical"},
    "Horn Drill": {"power": 100, "type": "Normal", "category": "Physical"},
    "Thrash": {"power": 120, "type": "Normal", "category": "Physical"},
    "Pound": {"power": 40, "type": "Normal", "category": "Physical"},
    "Disarming Voice": {"power": 40, "type": "Fairy", "category": "Special"},
    "Draining Kiss": {"power": 50, "type": "Fairy", "category": "Special"},
    "Moonblast": {"power": 95, "type": "Fairy", "category": "Special"},
    "Meteor Mash": {"power": 90, "type": "Steel", "category": "Physical"},
    "Psychic": {"power": 90, "type": "Psychic", "category": "Special"},
    "Flame Burst": {"power": 70, "type": "Fire", "category": "Special"},
    "Hex": {"power": 65, "type": "Ghost", "category": "Special"},
    "Extra Sensory": {"power": 80, "type": "Psychic", "category": "Special"},
    "Dazzling Gleam": {"power": 80, "type": "Fairy", "category": "Special"},
    "Hyper Voice": {"power": 90, "type": "Normal", "category": "Special"},
    "Absorb": {"power": 20, "type": "Grass", "category": "Special"},
    "Astonish": {"power": 30, "type": "Ghost", "category": "Physical"},
    "Air Cutter": {"power": 60, "type": "Flying", "category": "Special"},
    "Leech Life": {"power": 80, "type": "Bug", "category": "Physical"},
    "Mega Drain": {"power": 40, "type": "Grass", "category": "Special"},
    "Giga Drain": {"power": 75, "type": "Grass", "category": "Special"},
    "Petal Dance": {"power": 120, "type": "Grass", "category": "Special"},
    "Sludge Bomb": {"power": 90, "type": "Poison", "category": "Special"},
    "Fury Cutter": {"power": 40, "type": "Bug", "category": "Physical"},
    "Signal Beam": {"power": 75, "type": "Bug", "category": "Special"},
    "Mud Bomb": {"power": 65, "type": "Ground", "category": "Special"},
    "Tri Attack": {"power": 80, "type": "Normal", "category": "Special"},
    "Fissure": {"power": 100, "type": "Ground", "category": "Physical"},
    "Pay Day": {"power": 40, "type": "Normal", "category": "Physical"},
    "Fury Swipes": {"power": 18, "type": "Normal", "category": "Physical"},
    "Night Slash": {"power": 70, "type": "Dark", "category": "Physical"},
    "Power Gem": {"power": 80, "type": "Rock", "category": "Special"},
    "Play Rough": {"power": 90, "type": "Fairy", "category": "Physical"},
    "Zen Headbutt": {"power": 80, "type": "Psychic", "category": "Physical"},
    "Surf": {"power": 90, "type": "Water", "category": "Special"},
    "Aqua Tail": {"power": 90, "type": "Water", "category": "Physical"},
    "Low Kick": {"power": 50, "type": "Fighting", "category": "Physical"},
    "Karate Chop": {"power": 50, "type": "Fighting", "category": "Physical"},
    "Cross Chop": {"power": 100, "type": "Fighting", "category": "Physical"},
    "Close Combat": {"power": 120, "type": "Fighting", "category": "Physical"},
    "Rage": {"power": 50, "type": "Normal", "category": "Physical"},
    "Outrage": {"power": 120, "type": "Dragon", "category": "Physical"},
    "Flame Wheel": {"power": 60, "type": "Fire", "category": "Physical"},
    "Take Down": {"power": 90, "type": "Normal", "category": "Physical"},
    "Extreme Speed": {"power": 80, "type": "Normal", "category": "Physical"},
    "Flare Blitz": {"power": 120, "type": "Fire", "category": "Physical"},
    "Mud Shot": {"power": 55, "type": "Ground", "category": "Special"},
    "Waterfall": {"power": 80, "type": "Water", "category": "Physical"},
    "Dynamic Punch": {"power": 100, "type": "Fighting", "category": "Physical"},
    "Submission": {"power": 80, "type": "Fighting", "category": "Physical"},
    "Flash": {"power": 20, "type": "Normal", "category": "Special"},
    "Night Shade": {"power": 60, "type": "Ghost", "category": "Special"},
    "Shadow Ball": {"power": 80, "type": "Ghost", "category": "Special"},
    "Future Sight": {"power": 120, "type": "Psychic", "category": "Special"},
    "Focus Blast": {"power": 120, "type": "Fighting", "category": "Special"},
    "Seismic Toss": {"power": 60, "type": "Fighting", "category": "Physical"},
    "Revenge": {"power": 60, "type": "Fighting", "category": "Physical"},
    "Vital Throw": {"power": 70, "type": "Fighting", "category": "Physical"},
    "Leaf Blade": {"power": 90, "type": "Grass", "category": "Physical"},
    "Rock Throw": {"power": 50, "type": "Rock", "category": "Physical"},
    "Magnitude": {"power": 70, "type": "Ground", "category": "Physical"},
    "Rock Slide": {"power": 75, "type": "Rock", "category": "Physical"},
    "Stone Edge": {"power": 100, "type": "Rock", "category": "Physical"},
    "Explosion": {"power": 250, "type": "Normal", "category": "Physical"},
    "Heavy Slam": {"power": 100, "type": "Steel", "category": "Physical"},
    "Stomp": {"power": 65, "type": "Normal", "category": "Physical"},
    "Flame Charge": {"power": 50, "type": "Fire", "category": "Physical"},
    "Scald": {"power": 80, "type": "Water", "category": "Special"},
    "Discharge": {"power": 80, "type": "Electric", "category": "Special"},
    "Zap Cannon": {"power": 120, "type": "Electric", "category": "Special"},
    "Brave Bird": {"power": 120, "type": "Flying", "category": "Physical"},
    "Pluck": {"power": 60, "type": "Flying", "category": "Physical"},
    "Jump Kick": {"power": 100, "type": "Fighting", "category": "Physical"},
    "Headbutt": {"power": 70, "type": "Normal", "category": "Physical"},
    "Icy Wind": {"power": 55, "type": "Ice", "category": "Special"},
    "Aurora Beam": {"power": 65, "type": "Ice", "category": "Special"},
    "Ice Beam": {"power": 90, "type": "Ice", "category": "Special"},
    "Sheer Cold": {"power": 100, "type": "Ice", "category": "Special"},
    "Sludge": {"power": 65, "type": "Poison", "category": "Special"},
    "Icicle Spear": {"power": 25, "type": "Ice", "category": "Physical"},
    "Razor Shell": {"power": 75, "type": "Water", "category": "Physical"},
    "Spike Cannon": {"power": 20, "type": "Normal", "category": "Physical"},
    "Lick": {"power": 30, "type": "Ghost", "category": "Physical"},
    "Smog": {"power": 30, "type": "Poison", "category": "Special"},
    "Dark Pulse": {"power": 80, "type": "Dark", "category": "Special"},
    "Shadow Punch": {"power": 60, "type": "Ghost", "category": "Physical"},
    "Rock Tomb": {"power": 60, "type": "Rock", "category": "Physical"},
    "Iron Tail": {"power": 100, "type": "Steel", "category": "Physical"},
    "Bubble": {"power": 40, "type": "Water", "category": "Special"},
    "Vice Grip": {"power": 55, "type": "Normal", "category": "Physical"},
    "Crabhammer": {"power": 100, "type": "Water", "category": "Physical"},
    "Metal Claw": {"power": 50, "type": "Steel", "category": "Physical"},
    "Hyper Beam": {"power": 150, "type": "Normal", "category": "Special"},
    "Swift": {"power": 60, "type": "Normal", "category": "Special"},
    "Barrage": {"power": 15, "type": "Normal", "category": "Physical"},
    "Bullet Seed": {"power": 25, "type": "Grass", "category": "Physical"},
    "Wood Hammer": {"power": 120, "type": "Grass", "category": "Physical"},
    "Bone Club": {"power": 65, "type": "Ground", "category": "Physical"},
    "Bonemerang": {"power": 50, "type": "Ground", "category": "Physical"},
    "Bone Rush": {"power": 25, "type": "Ground", "category": "Physical"},
    "Double Kick": {"power": 30, "type": "Fighting", "category": "Physical"},
    "Rolling Kick": {"power": 60, "type": "Fighting", "category": "Physical"},
    "Mega Kick": {"power": 120, "type": "Fighting", "category": "Physical"},
    "High Jump Kick": {"power": 130, "type": "Fighting", "category": "Physical"},
    "Comet Punch": {"power": 18, "type": "Normal", "category": "Physical"},
    "Mach Punch": {"power": 40, "type": "Fighting", "category": "Physical"},
    "Fire Punch": {"power": 75, "type": "Fire", "category": "Physical"},
    "Ice Punch": {"power": 75, "type": "Ice", "category": "Physical"},
    "Thunder Punch": {"power": 75, "type": "Electric", "category": "Physical"},
    "Mega Punch": {"power": 80, "type": "Normal", "category": "Physical"},
    "Drain Punch": {"power": 75, "type": "Fighting", "category": "Physical"},
    "Power Whip": {"power": 120, "type": "Grass", "category": "Physical"},
    "Clear Smog": {"power": 50, "type": "Poison", "category": "Special"},
    "Self-Destruct": {"power": 200, "type": "Normal", "category": "Physical"},
    "Double Hit": {"power": 35, "type": "Normal", "category": "Physical"},
    "Hammer Arm": {"power": 100, "type": "Fighting", "category": "Physical"},
    "Double Slap": {"power": 15, "type": "Normal", "category": "Physical"},
    "Egg Bomb": {"power": 100, "type": "Normal", "category": "Physical"},
    "Ancient Power": {"power": 60, "type": "Rock", "category": "Special"},
    "Fake Out": {"power": 40, "type": "Normal", "category": "Physical"},
    "Dizzy Punch": {"power": 70, "type": "Normal", "category": "Physical"},
    "Twister": {"power": 40, "type": "Dragon", "category": "Special"},
    "Dragon Pulse": {"power": 85, "type": "Dragon", "category": "Special"},
    "Powder Snow": {"power": 40, "type": "Ice", "category": "Special"},
    "Lava Plume": {"power": 80, "type": "Fire", "category": "Special"},
    "Brick Break": {"power": 75, "type": "Fighting", "category": "Physical"},
    "Guillotine": {"power": 100, "type": "Normal", "category": "Physical"},
    "Pursuit": {"power": 40, "type": "Dark", "category": "Physical"},
    "Flail": {"power": 60, "type": "Normal", "category": "Physical"},
    "Bounce": {"power": 85, "type": "Flying", "category": "Physical"},
    "Dragon Rage": {"power": 40, "type": "Dragon", "category": "Special"},
    "Ice Shard": {"power": 40, "type": "Ice", "category": "Physical"},
    "Struggle": {"power": 50, "type": "Normal", "category": "Physical"},
    "Muddy Water": {"power": 90, "type": "Water", "category": "Special"},
    "Constrict": {"power": 10, "type": "Normal", "category": "Physical"},
    "Aqua Jet": {"power": 40, "type": "Water", "category": "Physical"},
    "Iron Head": {"power": 80, "type": "Steel", "category": "Physical"},
    "High Horsepower": {"power": 95, "type": "Ground", "category": "Physical"},
    "Giga Impact": {"power": 150, "type": "Normal", "category": "Physical"},
    "Psycho Cut": {"power": 70, "type": "Psychic", "category": "Physical"},
    "Aura Sphere": {"power": 80, "type": "Fighting", "category": "Special"},
    "Psystrike": {"power": 100, "type": "Psychic", "category": "Special"},
    "Metronome": {"power": 50, "type": "Normal", "category": "Special"}
};
export default moves;
